#include <iostream>
#include <string>
#include <cstdlib>
#include <vector>
// Not using namespace std

/*
	Second Project Euler problem:

	Each new term in the Fibonacci sequence is generated by adding the 
	previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed 
	four million, find the sum of the even-valued terms.


*/

int main() {
	int fibNum1 = 1;
	int fibNum2 = 2;
	int fibSum = 2;
	

	while (fibNum2 < 4000000) {
		int temp = fibNum2;
		fibNum2 = fibNum2 + fibNum1;
		fibNum1 = temp;
		if (fibNum2 > 4000000) {
			break;
		}
		else if (fibNum2 % 2 == 0) {
			fibSum += fibNum2;
		}
	}

	std::cout << fibSum << std::endl;
}